website/forms/ChangeAboutForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.validators import Length


class ChangeAboutForm(FlaskForm):
    about = TextAreaField("Расскажите о себе:", validators=[Length(0, 140)])
    submit = SubmitField('Изменить')

website/forms/ChangeAvatarForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, FileField
from wtforms.validators import DataRequired
from flask_wtf.file import FileAllowed


class ChangeAvatarForm(FlaskForm):
    avatar = FileField("Прикрепите изображение", validators=[DataRequired(), FileAllowed(['png', 'jpeg', 'jpg'], 'Неправильное расширение файла!')])
    submit = SubmitField('Изменить')

website/forms/ChangeEmailForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, EmailField
from wtforms.validators import DataRequired


class ChangeEmailForm(FlaskForm):
    email = EmailField("Введите имя:", validators=[DataRequired()])
    submit = SubmitField('Изменить')

website/forms/ChangeNameForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired


class ChangeNameForm(FlaskForm):
    name = StringField("Введите имя:", validators=[DataRequired()])
    submit = SubmitField('Изменить')

website/forms/ChangePasswordForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class ChangePasswordForm(FlaskForm):
    old_password = StringField("Введите старый пароль", validators=[DataRequired()])
    new_password = StringField("Введите новый пароль", validators=[DataRequired()])
    repeat_new_password = StringField("Повторите новый пароль", validators=[DataRequired()])
    submit = SubmitField('Изменить')

website/forms/FeedbackForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.validators import Length


class FeedbackForm(FlaskForm):
    feedback = TextAreaField("Задайте вопрос или сообщите об ошибке:", validators=[Length(0, 140)])
    submit = SubmitField('Отправить')

website/forms/LoginForm.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, BooleanField, SubmitField, EmailField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    email = EmailField('Почта', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

website/forms/PasswordRecoveryForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, EmailField
from wtforms.validators import DataRequired


class PasswordRecoveryForm(FlaskForm):
    email = EmailField('Введите почту, на которую зарегистрирован аккаунт', validators=[DataRequired()])
    submit = SubmitField('Отправить')

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash, current_app
from flask_login import login_user, login_required, logout_user, current_user
from .forms.LoginForm import LoginForm
from .forms.RegisterForm import RegisterForm
from .forms.PasswordRecoveryForm import PasswordRecoveryForm
from .forms.ResetPasswordForm import ResetPasswordForm
from data.users import User
from data import db_session
from .mail.mail import send_mail

auth = Blueprint("auth", __name__, template_folder="../templates")


# Авторизация
@auth.route("/login", methods=['GET', 'POST'])
def login():
    if not current_user.is_anonymous:
        abort(404)
    form = LoginForm()
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            current_app.logger.info(f"User has logged in: {current_user}")
            flash("Вы вошли в аккаунт!", category="success")
            return redirect(url_for('views.home'))
        flash("Неправильный логин или пароль.", category="error")
    return render_template("login.html", title='Авторизация', form=form, user=current_user)


# Регистрация
@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if not current_user.is_anonymous:
        abort(404)
    form = RegisterForm()
    if form.validate_on_submit():
        if form.password.data != form.password_again.data:
            flash("Пароли не совпадают!", "warning")
            return render_template("signup.html", title='Регистрация', form=form, user=current_user)
        db_sess = db_session.create_session()
        if db_sess.query(User).filter(User.email == form.email.data).first():
            flash("Такой пользователь уже есть!", "warning")
            return render_template("signup.html", title='Регистрация', form=form, user=current_user)
        user = User(
            name=form.name.data,
            email=form.email.data
        )
        user.set_password(form.password.data)
        db_sess.add(user)
        db_sess.commit()
        current_app.logger.info(f"New user has registered: {user}")
        flash("Вы зарегистрированы!", "success")
        return redirect(url_for('auth.login'))
    return render_template("signup.html", title='Регистрация', form=form, user=current_user)


# Выход из аккаунта
@auth.route('/logout')
@login_required
def logout():
    current_app.logger.info(f"User logged out: {current_user}")
    logout_user()
    flash("Вы вышли из аккаунта")
    return redirect("/")


# Восстановление пароля
@auth.route("/password_recovery", methods=['GET', 'POST'])
def password_recovery():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    
    
    form = PasswordRecoveryForm()
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        
        email = form.email.data
        
        user = db_sess.query(User).filter(User.email == email).first()
        
        if not user:
            flash("Что-то пошло не так... Возможно вы указали неверную почту", "error")
            return redirect(url_for('auth.login'))
        try:
            send_password_reset_email(user)
            current_app.logger.info(f"The recovery email has been sent to {user.email}")
            flash("Письмо отправлено на почту!", "success")
            return redirect(url_for('auth.login'))
        except TimeoutError:
            current_app.logger.warning(f"Timeout Error")
            flash("Что-то пошло не так... попробуйте чуть позже", "error")
            return redirect(url_for('auth.login'))
            
    return render_template("password_recovery.html", title="Сброс пароля", form=form, user=current_user)


# Отсылает письмо на указанную почту в user.email
def send_password_reset_email(user: User):
    token = user.get_reset_password_token()
    send_mail(user.email, "Восстановление пароля", html_body=render_template("email/email_template.html", user=user, token=token))


# Сбрасывает пароль
@auth.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    
    db_sess = db_session.create_session()
    user_id = User.verify_reset_password_token(token)
    
    if not user_id:
        return redirect(url_for('views.home'))
    
    user = db_sess.query(User).get(user_id)
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        
        user.set_password(form.password.data)
        db_sess.commit()
        
        current_app.logger.info(f"User has recovered the password: {current_user}")
        flash('Ваш пароль сброшен!', "success")
        return redirect(url_for('auth.login'))
    return render_template('reset_password.html', title='Сброс пароля', user=current_user, form=form)

website/views.py
from flask import Blueprint, render_template, flash, abort, redirect, url_for, request, jsonify, current_app
from flask_login import login_required, current_user
from data import db_session
from data.news_posts import NewsPost
from data.comments import Comment
from data.likes import Like
from data.users import User
from data.feedback import Feedback
from .forms.CreateCommentForm import CommentForm
from .forms.ChangePasswordForm import ChangePasswordForm
from .forms.ChangeAvatarForm import ChangeAvatarForm
from .forms.ChangeAboutForm import ChangeAboutForm
from .forms.FeedbackForm import FeedbackForm
from .forms.ChangeNameForm import ChangeNameForm
from .forms.ChangeEmailForm import ChangeEmailForm
from datetime import datetime
from sqlalchemy import func
import os

views = Blueprint("views", __name__, template_folder="../templates", static_url_path="../static")


# Домашняя страница
@views.route("/")
@views.route("/home")
def home():
    db_sess = db_session.create_session()

    posts = db_sess.query(NewsPost).all()[::-1]

    return render_template("home.html", title='Home', posts=posts, user=current_user)


# Лайк поста (приходит 'POST' запрос с помощью JS)
@views.route("/like/<int:post_id>", methods=['POST'])
@login_required
def like_post(post_id):
    db_sess = db_session.create_session()
    post = db_sess.query(NewsPost).get(post_id)
    if not post:
        current_app.logger.warning(f"Post doesn't exist: post_id={post_id}")
        flash('Такого поста ну существует!', 'error')
        return jsonify({'error': 'Post does not exist.'}, 400)
    like = db_sess.query(Like).filter(Like.author_id == current_user.id, Like.post_id == post_id).first()
    if like:
        db_sess.delete(like)
        db_sess.commit()
        current_app.logger.debug(f"User has liked post: {current_user}; post_id={post.id}")
    else:
        like = Like(
            author_id=current_user.id,
            post_id=post_id
        )
        db_sess.add(like)
        db_sess.commit()
        current_app.logger.debug(f"User has unliked post: {current_user}; post_id={post.id}")
    # back = request.referrer
    return jsonify({"likes": len(post.likes), "liked": current_user.id in map(lambda x: x.author_id, post.likes)})


# Просмотр поста
@views.route("/posts/<int:post_id>", methods=['GET', 'POST'])
@login_required
def view_post(post_id):
    form = CommentForm()
    db_sess = db_session.create_session()
    post = db_sess.query(NewsPost).get(post_id)
    if not post:
        current_app.logger.warning(f"Post doesn't exist: post_id={post_id}")
        flash("Такого поста не существует!", "error")
        abort(404)
    if form.validate_on_submit():

        if len(form.text.data) > 200:
            flash("Комментарий слишком длинный!", "warning")
            return render_template("post_with_comments.html", title='View post', post=post, form=form, user=current_user)
        new_comment_id = db_sess.query(func.max(Comment.id)).first()[0] + 1
        
        if form.files.data:
            files = form.files.data
            file_names = []
            # тут сохраняются файлы по принципу "static/img/user/content/{id поста}/{id комментария}/{номер изображения}.jpg"
            for i, file in enumerate(files):
                filename = f"static/img/user/content/{post_id}/{new_comment_id}/{i + 1}.jpg"
                file_names.append(filename.split('/', 1)[1])
                os.makedirs(os.path.dirname(filename), exist_ok=True)
                current_app.logger.info(f"User attached file: {current_user}; filename={filename}")
                
                with open(filename, 'wb') as f:
                    f.write(file.read())

        comment = Comment(
            text=form.text.data,
            author_id=current_user.id,
            post_id=post_id,
            images="; ".join(file_names)
        )
        db_sess.add(comment)
        db_sess.commit()
        current_app.logger.info(f"User has commented post: {current_user}; post_id={post.id}; comment_id={new_comment_id}")
        flash("Комментарий опубликован!", "success")
        return redirect(f"/posts/{post_id}")
        
    return render_template("post_with_comments.html", title='View post', post=post, form=form, user=current_user)


# Удаление комментария
@views.route("/delete-comment/<int:comment_id>")
@login_required
def delete_comment(comment_id):
    db_sess = db_session.create_session()
    comment = db_sess.query(Comment).get(comment_id)
    if not comment:
        current_app.logger.warning(f"Comment doesn't exist: comment_id={comment_id}")
        flash("Такого комментария не существует", "error")
        abort(404)
    if current_user.id != comment.author_id and not current_user.admin:
        current_app.logger.debug(f"User tried to delete someone else's comment: {current_user}; comment_id={comment_id}")
        abort(404)
    post_id = comment.post_id
    if comment.images:
        images = comment.images.split('; ')

        for image in images:
            os.remove("static/" + image)
        os.rmdir("static/" + '/'.join(image.split('/')[:-1]))
    db_sess.delete(comment)
    db_sess.commit()
    current_app.logger.info(f"User has deleted comment: {current_user}; post_id={post_id}; comment_id={comment_id}")
    flash("Комментарий удалён!", "success")
    return redirect(url_for('views.view_post', post_id=post_id))


# Редактирование комментария
@views.route("/edit-comment/<int:comment_id>", methods=['GET', 'POST'])
@login_required
def edit_comment(comment_id):
    form = CommentForm()
    db_sess = db_session.create_session()
    comment = db_sess.query(Comment).get(comment_id)
    if not comment:
        current_app.logger.warning(f"Comment doesn't exist: comment_id={comment_id}")
        flash("Такого комментария не существует", "error")
        abort(404)
    if current_user.id != comment.author_id:
        current_app.logger.debug(f"User tried to delete someone else's comment: {current_user}; comment_id={comment_id}")
        abort(404)
    
    if form.validate_on_submit():
        post_id = comment.post_id
        
        comment.text = form.text.data
        
        if comment.images:
            images = comment.images.split('; ')
            
            for image in images:
                os.remove("static/" + image)
            os.rmdir("static/" + '/'.join(image.split('/')[:-1]))
        
        files = form.files.data
        file_names = []
        
        for i, file in enumerate(files):
            if not file:
                continue
            filename = f"static/img/user/content/{post_id}/{comment_id}/{i + 1}.jpg"
            file_names.append(filename.split('/', 1)[1])
            os.makedirs(os.path.dirname(filename), exist_ok=True)
            
            current_app.logger.info(f"User attached file: {current_user}; filename={filename}")
            
            with open(filename, 'wb') as f:
                f.write(file.read())
        
        comment.images = "; ".join(file_names)
        
        current_app.logger.info(f"User edited comment: {current_user}; comment_id={comment_id}")
        
        db_sess.commit()
        return redirect(url_for('views.view_post', post_id=comment.post_id))
    form.text.data = comment.text
    
    return render_template("edit_comment.html", title='Edit comment', comment=comment, form=form, user=current_user)


# Просмотр профиля
@views.route("/profile")
@login_required
def view_profile():
    current_app.logger.debug(f"User opened profile: {current_user}")
    return render_template("user_profile.html", title='Профиль', user=current_user)


# Изменение пароля
@views.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        old_password = form.old_password.data
        new_password = form.new_password.data
        repeat_new_password = form.repeat_new_password.data
        
        user = db_sess.query(User).get(current_user.id)
        if not user.check_password(old_password):
            current_app.logger.debug(f"User entered an incorrect password: {current_user}")
            flash("Вы ввели неправильный пароль!", "error")
            return redirect(url_for('views.view_profile'))
        
        if new_password != repeat_new_password:
            current_app.logger.debug(f"Passwords don't match: {current_user}")
            flash("Пароли не совпадают!", "error")
            return redirect(url_for('views.view_profile'))
        
        user.set_password(new_password)
        db_sess.commit()
        
        current_app.logger.info(f"User changed password: {current_user}")
        
        flash("Пароль успешно изменён!", "success")
        return redirect(url_for('views.view_profile'))
    return render_template("change_password.html", title='Изменение пароля', form=form, user=current_user)


# Изменение аватара
@views.route('/change_avatar', methods=['GET', 'POST'])
@login_required
def change_avatar():
    form = ChangeAvatarForm()
    if form.validate_on_submit():
        image = request.files.get('avatar')

        with open(f"static/img/user/avatars/avatar_{current_user.id}.jpg", 'wb') as f:
            f.write(image.read())
        
        current_app.logger.info(f"User changed avatar: {current_user}")
        
        flash("Аватар успешно изменён!", "success")
        return redirect(url_for('views.view_profile'))
    return render_template("change_avatar.html", title="Изменение аватара", form=form, user=current_user)


# Конвертирует дату в "{количество времени} назад"
@views.app_template_filter("time_ago")
def time_ago(start_time):
    end_time = datetime.now()
    diff = datetime.now() - start_time
    
    seconds = diff.seconds + diff.days * 24 * 3600
    minutes = seconds // 60
    hours = minutes // 60
    days = diff.days

templates/base.html
{% from "components/toast.html" import toast %}
{% from "components/user_avatar.html" import user_avatar %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{{url_for('static', filename='img/icon/favicon.ico')}}" sizes="48x48" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <title>{{title}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="z-index: 11;">
      <div class="container-fluid">
        <a class="navbar-brand" id="site_logo" href="{{url_for('views.home')}}"><img src="{{url_for('static', filename='img/logo_timur.png')}}" style="width: 150px; height: 27px;"alt=""></a>

        <button 
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#my_navbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-grow-1" id="my_navbar">
          <div class="navbar-nav ms-auto flex-nowrap text-end">
            {% if user.is_authenticated %}
              {% if user.admin %}
                <a class="nav-item nav-link menu-item" href="{{url_for('admin.admin_panel')}}">Admin panel</a>
              {% endif %}
              <div class="dropdown">
                <a class="nav-item nav-link" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false"><div class="d-flex align-items-center justify-content-end">
                  <div>{{user.name}}</div>
                  <div>⠀</div>
                  <div>{{user_avatar(user.id, 25)}}</div>
                </div></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                  <li><a class="dropdown-item" href="{{url_for('views.view_profile')}}"><i class="bi bi-person-circle"></i> Профиль</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{{url_for('views.send_feedback')}}"><i class="bi bi-envelope"></i> Обратная связь</a></li>
                  <li><a class="dropdown-item" href="{{url_for('auth.logout')}}"><i class="bi bi-box-arrow-right"></i> Выйти</a></li>
                </ul>
              </div>
            {% else %}
              <a class="nav-item nav-link menu-item" href="{{url_for('auth.login')}}">Login</a>
              <a class="nav-item nav-link menu-item" href="{{url_for('auth.sign_up')}}">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
      <div aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-absolute top-0 end-0 p-3">
        {% for category, message in messages %}
          {{ toast(message=message, category=category) }}
        {% endfor %}
      </div>
    </div>
      {% endif %}
    {% endwith %}
    <div class="container">{% block content %}{% endblock %}</div>
  </body>
</html>

templates/change_about.html
{% extends "base.html" %}

{% block content %}

<div class="container row">
    <div class="col-lg-5 col-sm-7 mx-auto">
  <form method="POST">
    <a class="btn btn-primary" href="{{url_for('views.view_profile')}}">Назад</a>
    <h3 align="center">О себе</h3>
    {{ form.hidden_tag() }}
    <p>
        {{ form.about.label }}<br>
        {{ form.about(class="form-control") }}<br>
        {% for error in form.about.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </p>
    <p>{{ form.submit(type="submit", class="btn btn-primary mx-auto d-block col-lg-3 col-sm-5") }}</p>
  </form>
  </div>


{% endblock %}

templates/change_avatar.html
{% extends "base.html" %}

{% block content %}

<div class="container row">

    <div class="col-lg-5 col-sm-7 mx-auto">
  <form method="POST" action="" enctype="multipart/form-data">
    <a class="btn btn-primary" href="{{url_for('views.view_profile')}}">Назад</a>
    <h3 align="center">Изменение аватара</h3>
    {{ form.hidden_tag() }}
    <p>
        {{ form.avatar.label }}<br>
        {{ form.avatar(class="form-control") }}<br>
        {% for error in form.avatar.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </p>
    <p>{{ form.submit(type="submit", class="btn btn-primary mx-auto d-block col-lg-3 col-sm-5") }}</p>
    {% if message %}
        <div class="alert alert-warning" role="alert">
          {{message}}
      </div>
    {% endif %}
  </form>
  </div>


{% endblock %}

templates/change_email.html
{% extends "base.html" %}

{% block content %}

<div class="container row">
    <div class="col-lg-5 col-sm-7 mx-auto">
  <form method="POST">
    <a class="btn btn-primary" href="{{url_for('views.view_profile')}}">Назад</a>
    <h3 align="center">Изменить почту</h3>
    {{ form.hidden_tag() }}
    <p>
        {{ form.email.label }}<br>
        {{ form.email(class="form-control") }}<br>
        {% for error in form.email.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </p>
    <p>{{ form.submit(type="submit", class="btn btn-primary mx-auto d-block col-lg-3 col-sm-5") }}</p>
  </form>
  </div>


{% endblock %}

templates/change_name.html
{% extends "base.html" %}

{% block content %}

<div class="container row">
    <div class="col-lg-5 col-sm-7 mx-auto">
  <form method="POST">
    <a class="btn btn-primary" href="{{url_for('views.view_profile')}}">Назад</a>
    <h3 align="center">Изменить имя</h3>
    {{ form.hidden_tag() }}
    <p>
        {{ form.name.label }}<br>
        {{ form.name(class="form-control") }}<br>
        {% for error in form.name.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </p>
    <p>{{ form.submit(type="submit", class="btn btn-primary mx-auto d-block col-lg-3 col-sm-5") }}</p>
  </form>
  </div>


{% endblock %}

templates/change_password.html
{% extends "base.html" %}

{% block content %}

<div class="container row">
    <div class="col-lg-5 col-sm-7 mx-auto">
  <form method="POST">
    <a class="btn btn-primary" href="{{url_for('views.view_profile')}}">Назад</a>
    <h3 align="center">Изменение пароля</h3>
    {{ form.hidden_tag() }}
    <p>
        {{ form.old_password.label }}<br>
        {{ form.old_password(class="form-control") }}<br>
        {% for error in form.old_password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </p>
    <p>
        {{ form.new_password.label }}<br>
        {{ form.new_password(class="form-control") }}<br>
        {% for error in form.new_password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </p>
    <p>
        {{ form.repeat_new_password.label }}<br>
        {{ form.repeat_new_password(class="form-control") }}<br>
        {% for error in form.repeat_new_password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </p>
    <p>{{ form.submit(type="submit", class="btn btn-primary mx-auto d-block col-lg-3 col-sm-5") }}</p>
  </form>
  </div>


{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content%}

<div class="container row">
  <div class="col-lg-5 col-sm-7 mx-auto">
<form method="POST">
  <h3 align="center">Вход</h3>
  {{ form.hidden_tag() }}
  <p>
      {{ form.email.label }}<br>
      {{ form.email(class="form-control", type="email") }}<br>
      {% for error in form.email.errors %}
          <div class="alert alert-danger" role="alert">
              {{ error }}
          </div>
      {% endfor %}
  </p>
  <p>
      {{ form.password.label }}<br>
      {{ form.password(class="form-control", type="password") }}<br>
      {% for error in form.password.errors %}
          <div class="alert alert-danger" role="alert">
              {{ error }}
          </div>
      {% endfor %}
  </p>
  <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
  <p>{{ form.submit(type="submit", class="btn btn-primary mx-auto d-block col-lg-3 col-sm-5") }}</p>
  {% if message %}
      <div class="alert alert-warning" role="alert">
        {{message}}
    </div>
  {% endif %}
  <p><a href="{{url_for('auth.sign_up')}}">Нет аккаунта? Зарегистрироваться</a><br><br>
    <a href="{{url_for('auth.password_recovery')}}">Забыли пароль?</a></p>
</form>
</div>
</div>
{% endblock %}

templates/user_profile.html
{% extends "base.html" %}
{% from "components/user_avatar.html" import user_avatar %}

{% block content %}

<div class="card">
    <div class="card-body">
        <div class="d-sm-flex align-items-center">
            <div class="mr-auto">
                <div>
                    {{ user_avatar(user.id, 100) }}
                    <a class="btn btn-outline-secondary btn-sm" href="{{url_for('views.change_avatar')}}"><i class="bi bi-pencil-square"></i> Изменить фото</a>
                </div>
            <h1>{{user.name}}</h1>
            <a class="btn btn-primary btn-sm" href="{{url_for('views.change_name')}}">Изменить</a>
        </div>


        </div>
        <div class="d-flex flex-column">
            <hr>
            <h6 class="card-title">Подробная информация о пользователе:</h6>
            <br>
            <div class="card">
                <div class="card-header">
                    <strong>О себе:</strong>
                </div>
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <p>
                    {% if user.about %}
                    {% autoescape false %}
                    {% set break = '<' ~ 'br' ~ '>' %}
                        {{user.about|replace('\n', break) }}
                    {% endautoescape %}
                    {% else %}
                        Расскажите о себе =)
                    {% endif %}
                    </p>
                    <br><a class="btn btn-primary btn-sm" href="{{url_for('views.edit_about')}}">Изменить</a></p>
                  </blockquote>
                </div>
              </div>
            <br>
            <p class="card-text"><strong>Адрес электронной почты</strong><br>
                {{user.email}}<br>
                <a class="btn btn-primary btn-sm" href="{{url_for('views.change_email')}}">Изменить</a>
            </p>
            <p class="card-text"><strong>Пароль</strong><br>
                ********<br>
                <a class="btn btn-primary btn-sm" href="{{url_for('views.change_password')}}">Изменить</a></p>
        </div>
    </div>
</div>

{% endblock %}